### ISSUE TITLE
关于论文方面的问题，请教梁老师

### ISSUE THREAD

**Issue by rgs6655** [le-liang/MARLspectrumSharingV2X#12]
老师您好，我在您的“Spectrum Sharing in Vehicular Networks Based on Multi-Agent Reinforcement Learning”一文中，没有看到显式的优化问题的构建，想请问下在基于RL的资源分配中，优化问题的构建是必须的吗？

实际上在我的研究中，就直接将优化的目标呈现在reward中了，而没有构建优化问题的过程。经过实验，也达成了算法收敛以及与baseline算法对比的性能优化，想请问下您这样的研究流程是有问题的吗？

（我在念研究生二年级，刚经历过中期答辩，报告中没有体现出优化问题，但是状态、奖励的构建都有写明，还是被答辩老师批评了）TAT

**Comment by le-liang** [comment]
> 老师您好，我在您的“Spectrum Sharing in Vehicular Networks Based on Multi-Agent Reinforcement Learning”一文中，没有看到显式的优化问题的构建，想请问下在基于RL的资源分配中，优化问题的构建是必须的吗？
> 
> 实际上在我的研究中，就直接将优化的目标呈现在reward中了，而没有构建优化问题的过程。经过实验，也达成了算法收敛以及与baseline算法对比的性能优化，想请问下您这样的研究流程是有问题的吗？
> 
> （我在念研究生二年级，刚经历过中期答辩，报告中没有体现出优化问题，但是状态、奖励的构建都有写明，还是被答辩老师批评了）TAT

同学你好，我的观点是构建数学优化问题是解决资源分配的一种有效途径，但并非唯一方法（当然也可以说任何设计本质都在进行某种意义上的优化，不过这个有点太宽泛）。RL可以用来解决你构建好的优化问题，也可以直接去针对设计目标进行学习，而不通过显式得构建优化问题，这个观点我在下面的文章里有提到：

Deep-learning-based wireless resource allocation with application to vehicular networks
L. Liang, H. Ye, G. Yu, and G. Y. Li, Proceedings of the IEEE, vol. 108, no. 2, pp. 341-356, Feb. 2020.

当然这个见仁见智，你们老师可能有不同的观点吧。希望你研究顺利。

**Comment by rgs6655** [comment]
> > 老师您好，我在您的“Spectrum Sharing in Vehicular Networks Based on Multi-Agent Reinforcement Learning”一文中，没有看到显式的优化问题的构建，想请问下在基于RL的资源分配中，优化问题的构建是必须的吗？
> > 实际上在我的研究中，就直接将优化的目标呈现在reward中了，而没有构建优化问题的过程。经过实验，也达成了算法收敛以及与baseline算法对比的性能优化，想请问下您这样的研究流程是有问题的吗？
> > （我在念研究生二年级，刚经历过中期答辩，报告中没有体现出优化问题，但是状态、奖励的构建都有写明，还是被答辩老师批评了）TAT
> 
> 同学你好，我的观点是构建数学优化问题是解决资源分配的一种有效途径，但并非唯一方法（当然也可以说任何设计本质都在进行某种意义上的优化，不过这个有点太宽泛）。RL可以用来解决你构建好的优化问题，也可以直接去针对设计目标进行学习，而不通过显式得构建优化问题，这个观点我在下面的文章里有提到：
> 
> Deep-learning-based wireless resource allocation with application to vehicular networks
> L. Liang, H. Ye, G. Yu, and G. Y. Li, Proceedings of the IEEE, vol. 108, no. 2, pp. 341-356, Feb. 2020.
> 
> 当然这个见仁见智，你们老师可能有不同的观点吧。希望你研究顺利。

感谢您的回复！

也希望您研究顺利！
