### ISSUE TITLE
关于车辆时延部分在奖励函数的考虑

### ISSUE THREAD

**Issue by godmanbely** [le-liang/MARLspectrumSharingV2X#2]
梁老师，你好。

![1574839992(1)](https://user-images.githubusercontent.com/37969212/69703046-7c021a80-112b-11ea-8928-1a5412b0ae9d.jpg)

这里对奖励函数时延部分与论文里说的不太符合。而且一般优化时延是通过mac层或者物理层进行排队分析。所以时延部分一般在车联网中要怎么进行表达？而且在强化学习中怎么优化时延？
期待得到您的回复。  谢谢

**Comment by le-liang** [comment]
你好，reward和论文描述是一致的，只是同比缩小使得论文中的beta = 1。

关于时延，排队论可以用来分析，我们之前有相关的一些工作（附文末）。但这里主要想解决periodic payload of V2V links，即“在固定时间T内成功传输B字节数据”这样一个传统方案不太好描述的服务要求（也可以理解为不是非常典型的时延问题），因而尝试使用RL来解决。


Resource allocation for vehicular communications with low latency and high reliability, C. Guo, L. Liang, and G. Y. Li, IEEE Transactions on Wireless Communications, vol. 18, no. 8, pp. 3887–3902, Aug. 2019.

**Comment by godmanbely** [comment]
非常感想
