### ISSUE TITLE
Position of the Base Station

### ISSUE THREAD

**Issue by farzanullah** [le-liang/MARLspectrumSharingV2X#22]
In the code, the height and width of the cell are given as:
width = 750/2
height = 1298/2

Whereas, in Environment_marl.py file, the location of Base Station is defined as:
self.BS_position = [750 / 2, 1299 / 2]  # center of the grids

My question is, according to the code, the BS is located at the corner of the cell, rather than the center as mentioned in comment. Is there any specific reason for placing the BS at the corner?
Any help would be highly appreciated.

**Comment by le-liang** [comment]
Thanks for the comment. The height and width of the cell was divided by 2 to purposely improve V2V/V2I channel strengths by avoiding spreading the vehicles too sparsely in the cell. The BS position followed the original full-size setting and was supposed to be at the center. We forgot to chanege it accordingly, but don't expect too much difference in the final results.
