### ISSUE TITLE
关于仿真中位置模拟

### ISSUE THREAD

**Issue by pazyork** [le-liang/MARLspectrumSharingV2X#27]
![image](https://user-images.githubusercontent.com/34975240/194457363-1d54269b-9074-46c5-8d95-4036af53ddff.png)
在训练阶段，在单次episode里，车辆的位置不更新是出于什么样的考虑呢？ 为什么要100次才更新一次呢？

**Comment by huangkk99** [comment]
我们固定大尺度衰落一段时间，仅依赖小尺度衰落造成的动态性进行训练，能够帮助提高训练过程的稳定性。
