### ISSUE TITLE
关于get_state函数的问题

### ISSUE THREAD

**Issue by xiangli-bjtu** [le-liang/MARLspectrumSharingV2X#6]
梁老师您好，想请教下关于主程序main_marl_train.py中的get_state()函数。为什么在创建环境env时，明明已经计算好了信道慢衰落和快衰落的数值，还要在这个函数里重新计算一遍V2V_fast, V2V_abs, V2I_fast, V2I_abs作为真实输入网络中的状态值。想问下这个计算公式是怎么考虑的？

![image](https://user-images.githubusercontent.com/45653880/89746613-3e90c200-daed-11ea-9d6b-b6ef5cfe9a1f.png)

**Comment by le-liang** [comment]
> 梁老师您好，想请教下关于主程序main_marl_train.py中的get_state()函数。为什么在创建环境env时，明明已经计算好了信道慢衰落和快衰落的数值，还要在这个函数里重新计算一遍V2V_fast, V2V_abs, V2I_fast, V2I_abs作为真实输入网络中的状态值。想问下这个计算公式是怎么考虑的？
> 
> ![image](https://user-images.githubusercontent.com/45653880/89746613-3e90c200-daed-11ea-9d6b-b6ef5cfe9a1f.png)

This is to roughly normalize DQN inputs for the ease of training. The numbers are obtained from several trial runs.
