### ISSUE TITLE
Error in code?

### ISSUE THREAD

**Issue by farzanullah** [le-liang/MARLspectrumSharingV2X#8]
In Environment_MARL.py line 110,
the code is 
self.V2I_power = 10 ** (self.V2I_power_dB)

however i think the line should be
self.V2I_power = 10 ** (self.V2I_power_dB / 10)

is this correct?

**Comment by le-liang** [comment]
> In Environment_MARL.py line 110,
> the code is
> self.V2I_power = 10 ** (self.V2I_power_dB)
> 
> however i think the line should be
> self.V2I_power = 10 ** (self.V2I_power_dB / 10)
> 
> is this correct?

Thanks for pointing out this typo. Removed this line of redundant code since we worked directly with "_dB" throughout the program.
